### ISSUE TITLE
built file `drscala.jar` crash

### ISSUE THREAD

**Issue by vuphan314** [DrJavaAtRice/drjava#9]
Hello @ponderosaTX:

I have two almost-identical systems (both have 64-bit Ubuntu 17.04 with the same environment variables, Ant 1.9.8, and Oracle JDK 1.8.0_144). But my built file `drscala.jar` works on 1 system only. 

Everything is at commit: https://github.com/DrJavaAtRice/drjava/commit/95c212768e5537fb24fe46220bedcfde21faccc4

Successful build of `drscala.jar`:
- ```
  vu@Vu-Gazelle:~$ git clone https://github.com/DrJavaAtRice/drjava
  Cloning into 'drjava'...
  remote: Counting objects: 79118, done.
  remote: Total 79118 (delta 0), reused 0 (delta 0), pack-reused 79118
  Receiving objects: 100% (79118/79118), 250.97 MiB | 65.06 MiB/s, done.
  Resolving deltas: 100% (54338/54338), done.

- ```
  vu@Vu-Gazelle:~$ cd drjava/drjava/
  ```

- ```
  vu@Vu-Gazelle:~/drjava/drjava$ git checkout drscala/develop
  Branch drscala/develop set up to track remote branch drscala/develop from origin.
  Switched to a new branch 'drscala/develop'
  ```

- ```
  vu@Vu-Gazelle:~/repos/drjava/drjava$ ant jar
  Buildfile: /home/vu/repos/drjava/drjava/build.xml
       [echo] JAVA8_HOME=/usr/lib/jvm/java-8-oracle/'

  resolve-development-value:

  resolve-version-tag:

  generate-source:
       [echo] Processing src/edu/rice/cs/drjava/CodeStatus.orig
       [echo] Processing src/edu/rice/cs/drjava/Version.orig
       [copy] Copying 1 file to /home/vu/repos/drjava/drjava/src/edu/rice/cs/drjava

  resolve-java8-runtime:
  [available] DEPRECATED - <available> used to override an existing property.
  [available]   Build file should not reuse the same property name for different values.
       [echo] java8-runtime=/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar

  resolve-java8-tools:
       [echo] java8-tools='/usr/lib/jvm/java-8-oracle/lib/tools.jar

  do-compile:
       [echo] Compiling src directory to classes/base and classes/test with command 'javac'
       [move] Moving 499 files to /home/vu/repos/drjava/drjava/classes/base
      [javac] Compiling 587 source files to /home/vu/repos/drjava/drjava/classes/base
       [move] Moving 523 files to /home/vu/repos/drjava/drjava/classes/test

  copy-resources:
       [copy] Copying 7 files to /home/vu/repos/drjava/drjava/classes/base

  unjar-libs:
       [echo] JAVA8_HOME=/usr/lib/jvm/java-8-oracle/'

  check-generate-dir-from-dir:

  do-unjar-libs:

  compile:

  jar:
        [jar] Building jar: /home/vu/repos/drjava/drjava/drscala.jar

  BUILD SUCCESSFUL
  Total time: 7 seconds
  ```

Failed run of `drscala.jar`:
  ```
  vu@Vu-Gazelle:~/repos/drjava/drjava$ java -jar drscala.jar
  edu.rice.cs.util.UnexpectedException: java.lang.reflect.InvocationTargetException
  edu.rice.cs.util.UnexpectedException: java.lang.reflect.InvocationTargetException
  	at edu.rice.cs.util.swing.Utilities.invokeAndWait(Utilities.java:81)
  	at edu.rice.cs.drjava.ui.MainFrame.<init>(MainFrame.java:3027)
  	at edu.rice.cs.drjava.DrScalaRoot.main(DrScalaRoot.java:159)
  	at edu.rice.cs.drjava.DrScala.configureAndLoadDrScalaRoot(DrScala.java:290)
  	at edu.rice.cs.drjava.DrScala.main(DrScala.java:185)
  Caused by: java.lang.reflect.InvocationTargetException
  	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
  	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
  	at edu.rice.cs.util.swing.Utilities.invokeAndWait(Utilities.java:80)
  	... 4 more
  Caused by: java.lang.NoClassDefFoundError: edu/rice/cs/drjava/model/compiler/ScalaCompiler
  	at edu.rice.cs.drjava.model.AbstractDJDocument.<init>(AbstractDJDocument.java:139)
  	at edu.rice.cs.drjava.model.AbstractDJDocument.<init>(AbstractDJDocument.java:187)
  	at edu.rice.cs.drjava.model.repl.InteractionsDJDocument.<init>(InteractionsDJDocument.java:88)
  	at edu.rice.cs.drjava.model.AbstractGlobalModel.<init>(AbstractGlobalModel.java:277)
  	at edu.rice.cs.drjava.model.DefaultGlobalModel.<init>(DefaultGlobalModel.java:163)
  	at edu.rice.cs.drjava.ui.MainFrame$148.run(MainFrame.java:3035)
  	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
  	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
  	at java.awt.EventQueue.access$500(EventQueue.java:97)
  	at java.awt.EventQueue$3.run(EventQueue.java:709)
  	at java.awt.EventQueue$3.run(EventQueue.java:703)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
  	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
  	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
  Caused by: java.lang.ClassNotFoundException: edu.rice.cs.drjava.model.compiler.ScalaCompiler
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 20 more
  error thrown
  ```

Full error message in popup window:
  ```
  edu.rice.cs.util.UnexpectedException: java.lang.reflect.InvocationTargetException
  	at edu.rice.cs.util.swing.Utilities.invokeAndWait(Utilities.java:81)
  	at edu.rice.cs.drjava.ui.MainFrame.<init>(MainFrame.java:3027)
  	at edu.rice.cs.drjava.DrScalaRoot.main(DrScalaRoot.java:159)
  	at edu.rice.cs.drjava.DrScala.configureAndLoadDrScalaRoot(DrScala.java:290)
  	at edu.rice.cs.drjava.DrScala.main(DrScala.java:185)
  Caused by: java.lang.reflect.InvocationTargetException
  	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
  	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
  	at edu.rice.cs.util.swing.Utilities.invokeAndWait(Utilities.java:80)
  	... 4 more
  Caused by: java.lang.NoClassDefFoundError: edu/rice/cs/drjava/model/compiler/ScalaCompiler
  	at edu.rice.cs.drjava.model.AbstractDJDocument.<init>(AbstractDJDocument.java:139)
  	at edu.rice.cs.drjava.model.AbstractDJDocument.<init>(AbstractDJDocument.java:187)
  	at edu.rice.cs.drjava.model.repl.InteractionsDJDocument.<init>(InteractionsDJDocument.java:88)
  	at edu.rice.cs.drjava.model.AbstractGlobalModel.<init>(AbstractGlobalModel.java:277)
  	at edu.rice.cs.drjava.model.DefaultGlobalModel.<init>(DefaultGlobalModel.java:163)
  	at edu.rice.cs.drjava.ui.MainFrame$148.run(MainFrame.java:3035)
  	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
  	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
  	at java.awt.EventQueue.access$500(EventQueue.java:97)
  	at java.awt.EventQueue$3.run(EventQueue.java:709)
  	at java.awt.EventQueue$3.run(EventQueue.java:703)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
  	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
  	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
  Caused by: java.lang.ClassNotFoundException: edu.rice.cs.drjava.model.compiler.ScalaCompiler
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 20 more

  Caused by:
  java.lang.reflect.InvocationTargetException
  	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
  	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
  	at edu.rice.cs.util.swing.Utilities.invokeAndWait(Utilities.java:80)
  	at edu.rice.cs.drjava.ui.MainFrame.<init>(MainFrame.java:3027)
  	at edu.rice.cs.drjava.DrScalaRoot.main(DrScalaRoot.java:159)
  	at edu.rice.cs.drjava.DrScala.configureAndLoadDrScalaRoot(DrScala.java:290)
  	at edu.rice.cs.drjava.DrScala.main(DrScala.java:185)
  Caused by: java.lang.NoClassDefFoundError: edu/rice/cs/drjava/model/compiler/ScalaCompiler
  	at edu.rice.cs.drjava.model.AbstractDJDocument.<init>(AbstractDJDocument.java:139)
  	at edu.rice.cs.drjava.model.AbstractDJDocument.<init>(AbstractDJDocument.java:187)
  	at edu.rice.cs.drjava.model.repl.InteractionsDJDocument.<init>(InteractionsDJDocument.java:88)
  	at edu.rice.cs.drjava.model.AbstractGlobalModel.<init>(AbstractGlobalModel.java:277)
  	at edu.rice.cs.drjava.model.DefaultGlobalModel.<init>(DefaultGlobalModel.java:163)
  	at edu.rice.cs.drjava.ui.MainFrame$148.run(MainFrame.java:3035)
  	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
  	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
  	at java.awt.EventQueue.access$500(EventQueue.java:97)
  	at java.awt.EventQueue$3.run(EventQueue.java:709)
  	at java.awt.EventQueue$3.run(EventQueue.java:703)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
  	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
  	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
  Caused by: java.lang.ClassNotFoundException: edu.rice.cs.drjava.model.compiler.ScalaCompiler
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 20 more

  System Properties:
  DrScala Version drscala-20170829-032119
  DrScala Build Time 20170829-032119

  java.runtime.name = Java(TM) SE Runtime Environment
  sun.boot.library.path = /usr/lib/jvm/java-8-oracle/jre/lib/amd64
  java.vm.version = 25.144-b01
  java.vm.vendor = Oracle Corporation
  java.vendor.url = http://java.oracle.com/
  path.separator = :
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  file.encoding.pkg = sun.io
  user.country = US
  sun.java.launcher = SUN_STANDARD
  sun.os.patch.level = unknown
  java.vm.specification.name = Java Virtual Machine Specification
  user.dir = <anonymized user.home>/repos/drscala/drjava
  java.runtime.version = 1.8.0_144-b01
  java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
  java.endorsed.dirs = /usr/lib/jvm/java-8-oracle/jre/lib/endorsed
  os.arch = amd64
  java.io.tmpdir = /tmp
  line.separator = "\u000a"
  java.vm.specification.vendor = Oracle Corporation
  os.name = Linux
  sun.jnu.encoding = UTF-8
  java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
  sun.awt.enableExtraMouseButtons = true
  java.specification.name = Java Platform API Specification
  java.class.version = 52.0
  sun.management.compiler = HotSpot 64-Bit Tiered Compilers
  os.version = 4.10.0-33-generic
  user.home = <anonymized user.home>
  user.timezone = America/Chicago
  java.awt.printerjob = sun.print.PSPrinterJob
  file.encoding = UTF-8
  java.specification.version = 1.8
  java.class.path = drscala.jar
  user.name = <anonymized user.name>
  java.vm.specification.version = 1.8
  sun.java.command = drscala.jar
  java.home = /usr/lib/jvm/java-8-oracle/jre
  sun.arch.data.model = 64
  user.language = en
  java.specification.vendor = Oracle Corporation
  awt.toolkit = sun.awt.X11.XToolkit
  java.vm.info = mixed mode
  java.version = 1.8.0_144
  java.ext.dirs = /usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext
  sun.boot.class.path = /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes
  java.vendor = Oracle Corporation
  file.separator = /
  java.vendor.url.bug = http://bugreport.sun.com/bugreport/
  sun.font.fontmanager = sun.awt.X11FontManager
  sun.io.unicode.encoding = UnicodeLittle
  sun.cpu.endian = little
  sun.desktop = gnome
  sun.cpu.isalist =

  DrScala configuration file
  In resource bundle edu.rice.cs.drjava.config.options:
  	nothing

  In shadowed configuration:
  key.delete.next = [shift DELETE]
  key.delete.previous = [shift BACK_SPACE]
  quit.prompt = false
  default.compiler.preference = No Preference
  window.height = 964
  window.width = 958
  window.x = 1
  window.y = 52
  window.state = 4
  last.interactions.dir = <anonymized user.home>
  tabbedpanes.state = 960 540 700 400
  new.version.notification.last = 1503886416507

  Used memory: about 17.06 megabytes
  Free memory: about 335.44 megabytes
  Total memory: about 352.50 megabytes
  Total memory can expand to: about 6.96 gigabytes

  Number of processors/cores: 8
  ```

**Comment by vuphan314** [comment]
@ponderosaTX 
The problem is fixed by issuing `ant clean` before `ant jar`. 
Thank you.
